<?php
return [
	
	'ajax-user-details-json' => [
		'route_value' => '/ajax/user-details/json',
		'auth_check_requirements' => 'none',
		'page_filename' => '',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['GET'],
		'controller_type' => 'oop-mapped',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\AllUserDetails\GetController::class,
		'method_name' => 'ajaxJsonOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-user-details-xml' => [
		'route_value' => '/ajax/user-details/xml',
		'auth_check_requirements' => 'none',
		'page_filename' => '',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['GET'],
		'controller_type' => 'oop-mapped',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\AllUserDetails\GetController::class,
		'method_name' => 'ajaxXmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-user-details-html' => [
		'route_value' => '/ajax/user-details/html',
		'auth_check_requirements' => 'none',
		'page_filename' => '',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['GET'],
		'controller_type' => 'oop-mapped',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\AllUserDetails\GetController::class,
		'method_name' => 'ajaxHtmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-user-details-text' => [
		'route_value' => '/ajax/user-details/text',
		'auth_check_requirements' => 'none',
		'page_filename' => '',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['GET'],
		'controller_type' => 'oop-mapped',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\AllUserDetails\GetController::class,
		'method_name' => 'ajaxTextOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-procedural-user-details-json' => [
		'route_value' => '/ajax/procedural/user-details/json',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-procedural-user-details-json.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['GET'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxJsonOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-procedural-user-details-xml' => [
		'route_value' => '/ajax/procedural/user-details/xml',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-procedural-user-details-xml.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['GET'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxXmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-procedural-user-details-html' => [
		'route_value' => '/ajax/procedural/user-details/html',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-procedural-user-details-html.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['GET'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxHtmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-procedural-user-details-text' => [
		'route_value' => '/ajax/procedural/user-details/text',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-procedural-user-details-text.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['GET'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxTextOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-switchover-step-target-activity-rel-form-fields-html-get' => [
		'route_value' => '/ajax/switchover-step/target-activity-rel-form-fields-html/get',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-switchover-step-target-activity-rel-form-fields-html-get.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['POST'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxHtmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-dns-record-type-rel-form-fields-html-get' => [
		'route_value' => '/ajax/dns-record-type-rel-form-fields-html/get',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-dns-record-type-rel-form-fields-html-get.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['POST'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxHtmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-dmg-rel-form-fields-html-get' => [
		'route_value' => '/ajax/dmg-rel-form-fields-html/get',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-dmg-rel-form-fields-html-get.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['POST'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxHtmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-target-server-script-deployment-rel-form-fields-html-get' => [
		'route_value' => '/ajax/target-server-script-deployment-rel-form-fields-html/get',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-target-server-script-deployment-rel-form-fields-html-get.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['POST'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxHtmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-app-switchover-schedule-rel-form-fields-html-get' => [
		'route_value' => '/ajax/app-switchover-schedule-rel-form-fields-html/get',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-app-switchover-schedule-rel-form-fields-html-get.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['POST'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxHtmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
	'ajax-currently-live-from-info-change-manual-override' => [
		'route_value' => '/ajax/app-id/:routing_eng_var_3/currently-live-from-info-change/manual-override',
		'auth_check_requirements' => 'none',
		'page_filename' => 'ajax-currently-live-from-info-change-manual-override.php',
		'redirect_to' => '',
		'route_type' => 'ajax',
		'allowed_request_methods' => ['POST'],
		'controller_type' => 'procedural',
		'controller_class_name' => \EaseAppPHP\EABlueprint\App\Http\Controllers\ProceduralController::class,
		'method_name' => 'ajaxHtmlOutput',
		'with_middleware' => '',
		'without_middleware' => ''
	],
];